---
  consumer_key:     U1kqrImtiiAQIeLHuqvxw
  consumer_secret:  B5rz8e1WQcBKquXMBqjMqWjdAJB2Kq9F5oDB1U  
  token:            92175249-KnWzY7jdlrfIR3DVKJIB8wv1xjSnffmu0Nq5sGGhm
  secret:           JxfLH6L98ESl8Z0luCAOLSWEzhc2aGGhJ43bsBTAA
  user_bitly:       duke16
  key_bitly:        R_3deaa9026c5828aae99c01df82478629    
