#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
Bundler.require

require 'rake'
require 'string'
require 'scraper'
require 'updater'
require 'models'

config = YAML.load_file(File.expand_path("config.yml"))

Twitter.configure do |c|
  c.consumer_key = config['twitter']['consumer_key']
  c.consumer_secret = config['twitter']['consumer_secret']
  c.oauth_token = config['twitter']['oauth_token']
  c.oauth_token_secret = config['twitter']['oauth_token_secret']
end


Scraper.run!
Updater.now
